export const LOAD_PROJECTS = 'LOAD_PROJECTS'
export const LOAD_FIELDS = 'LOAD_FIELDS'
export const TOGGLE_EDIT_MODE = 'TOGGLE_EDIT_MODE'
export const UPDATE_PROJECT = 'UPDATE_PROJECT'
export const UPDATE_FIELD = 'UPDATE_FIELD'

export const CREATE_PROJECT = 'CREATE_PROJECT'
export const NEW_PROJECT = 'NEW_PROJECT'

export const NEW_FIELD = 'NEW_FIELD'
export const REMOVE_PROJECT = 'REMOVE_PROJECT'
